### PR TITLE
add ipynb version of notebook

### PR DESCRIPTION
**Pull request by clausmichele**
I added the iPython notebook version of the Quarto notebook.
I also asked to allow https://app.reviewnb.com/ to be added to this repo, so that it would be easier to compare notebooks.

### CODE REVIEW

**Comment by MartinSchobben** [comment]
Thanks for the input! I think it would be easier to add the following to the yaml header of the Quarto notebook.

```
execute:
    keep-ipynb: true
```

One of the reason I thought of using Quarto is that the Markdown-like syntax is easier to review on GitHub.

**Comment by clausmichele** [comment]
@MartinSchobben for me it's the same, my alternative would have been to use ReviewNB (example: https://app.reviewnb.com/interTwin-eu/openeo-flood-mapper-local/blob/main/notebooks%2F0_tutorial_local_proc.ipynb).

Anyway, I don't have Quarto installed locally, could you explain me how to proceed to modify the notebook interactively and then republish it as `.qmd` ? Or what's your usual way of doing that?

**Comment by MartinSchobben** [comment]
I don't know if it is the usual way. But the second benefit is that the `qmd` is easier to deploy as a gh page.  Or, at least, for me it is. It involves executing `quarto publish gh-pages document.qmd` from the notebooks directory.

Installation options can be found here: https://quarto.org/docs/get-started/. If that does not work for you, we can still consider switching.

**Comment by MartinSchobben** [comment]
I also don't know if we focus much on `0_tutorial_local_proc.ipynb`. Maybe @fl0roth has more to tell on that.

**Comment by clausmichele** [comment]
> I also don't know if we focus much on `0_tutorial_local_proc.ipynb`. Maybe @fl0roth has more to tell on that.

That notebook is just an example of openEO Client Side processing, but I used it to show you an example of how ReviewNB works.
I will install Quarto and let you know. However, in my opinion it would still be preferable to have both versions in the repo later on, so that the notebook could already be executed as is with Jupyter, Visual Studio, PyCharm, Spyder etc.

**Comment by MartinSchobben** [comment]
That should be fine by using the yaml output as defined above to preserve the ipynb. It basically still is a Jupyter notebook.

**Comment by fl0roth** [comment]
Yes, the `0_tutorial_local_proc.ipynb` is a leftover from the time when we set up the client-side processing and could be removed when not needed any more.

I think keeping a Jupyter notebook version would make sense, as it allows as to be quite flexible for further development.

**Comment by MartinSchobben** [comment]
So, if this all works then I would suggest adding:

```
execute:
    keep-ipynb: true
``` 
to the `notebooks/1_yeoda_dc` yaml header. This way we will preserve the `ipynb` next to the `qmd` file.  We can then work on the  `qmd` file and review change on GitHub.

**Comment by SchwammDev** [comment]
Adding ReviewNB is fine I think as it does fix the issues with comparing jupyter notebooks, however it means it still requires a third party solution to handle a fundamental problem of the jupyter data format.
So I'd also like to keep the Quarto format, because not everyone can or wants to work with ReviewNB and with Quarto I can more or less any diff tool I like.
So @MartinSchobben solution would work for me.

**Comment by clausmichele** [comment]
Then I think I can close this PR and wait until you add the exported ipynb version as well.

**Comment by MartinSchobben** [comment]
I'll export the ipynb then.

**Pull request closed without merging**
